apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hafiz
  labels:
    app: deployment-hafiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-hafiz
  template:
    metadata:
      labels:
        app: pod-hafiz
    spec:
      containers:
        - name: mysql
          image: mysql
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: configmap-hafiz
        - name: phpmyadmin
          image: phpmyadmin
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap-hafiz