apiVersion: v1
kind: Service
metadata:
  name: service-hafiz
  labels:
    app: service-hafiz
spec:
  selector:
    app: pod-hafiz
  ports:
    - name: phpmyadmin
      port: 8081
      targetPort: 80
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
